### ISSUE TITLE
no rd files built inside the 'bin' 

### ISSUE THREAD

**Issue by Niv94** [computations/root_digger#7] opened 2022-03-21 20:52 UTC
Dear team,

I downloaded the source code and built it using the 'cmake' command. Although the making seemed successful there were no 'rd' files inside the 'bin' directory. Could you please help?

Thank you in advance

**Comment by computations** [comment] 2022-03-21 22:24
Hey, thanks for the interest! This is a curious problem, do you have any logs of the compilation that you can share? I can only think of one way that this would happen, and that is if the compilation failed somehow.

**Comment by computations** [comment] 2022-04-06 22:08
Since it has been a while and I can't reproduce this bug, I am going to close the issue. If you still are experiencing the same problem, feel free to  open the issue again.

**Closed as completed by computations** 2022-04-06 22:08 UTC

**Comment by Niv94** [comment] 2022-04-18 22:54
Hi,

Thank you for your email. I apologize for the delayed response. I had been in the field. Yes here is how the log screen looked like after trying to compile the makefile. Please advise.

Thank you,
Nivi
