### ISSUE TITLE
Tree file could not be parsed

### ISSUE THREAD

**Issue by josenikhid97** [computations/root_digger#12] opened 2022-08-15 09:01 UTC
Hello !

I was running a dataset  with correct file names , correct file location and also data inside the files .  ./rd -- msa  --tree  and the tool shows an error " There was an error during processing , Tree file could not be parsed ". is there any way to overcome this problem. I am also attaching  the error.
![treefile](https://user-images.githubusercontent.com/64956458/184607334-d7ef9b64-781e-4f8c-824e-09809300044d.png)

Thank you in advance

**Comment by computations** [comment] 2022-08-15 16:57
Would it be possible for for you to send the tree? If that isn't possible, try to open the tree in another program like dendroscope or treefig, to make sure it is properly formatted.

**Comment by josenikhid97** [comment] 2022-08-16 13:33
sure, i can send you the tree file,but it  is large so i am not able to send you but it seems the format is correct because the newick format is the end product of one of the tool  i am using. so i am sending you the screenshot of the file format.
![tre](https://user-images.githubusercontent.com/64956458/184892437-57a711aa-a8c7-40ea-a901-89edfcc0aa52.png)

**Comment by computations** [comment] 2022-08-16 14:07
> newick format is the end product of one of the tool

Unfortunately, newick isn't super standardized, so this isn't a guarantee. 

I can't reproduce the problem based on the screenshot you sent me, so I think you are going to have to send me the tree file in order for me to solve the problem. 

Alternatively, you could switch to the coraxlib branch of RootDigger, and try with that version. That branch has a parser which might give much better error messages.

**Comment by josenikhid97** [comment] 2022-08-18 10:47
any possible way of sending you the tree file ?, i am sending the google drive link of the tree file and fasta file 

https://drive.google.com/file/d/1YiLcVRTpJEVtkp9fNTrGlN9rJzDUcqZb/view?usp=sharing

https://drive.google.com/file/d/1LE6JwcLWM7UWquUsA1bnqux7SkkAf2pl/view?usp=sharing

please let me know the problem

**Comment by computations** [comment] 2022-08-20 17:15
Thank you for the tree file and the alignment. I am on vacation at the moment, so I didn't get a ton of time to look at this. I don't know what is wrong with the parsing when using the `master` branch, but when using the `coraxlib` branch everything seems to work fine (I didn't let it run very long, but it never gave an error after about 5 min). 

The short story is that this has convinced me to finally just update the master branch to use coraxlib. This should fix your issue. Let me know if it doesn't.

**Comment by josenikhid97** [comment] 2022-08-21 08:17
sure , thank you . how to run on coraxlib, do i have to use any flag on the terminal command ?, or is it the general command ?

**Comment by computations** [comment] 2022-08-21 10:25
Sorry, I should have been clearer. v1.8.0 of RootDigger uses coraxlib by default. You just have to pull the new changes and rebuild the binary.

**Comment by josenikhid97** [comment] 2022-08-22 08:51
Great !!
Thank you so much for your time and have a great time spending your vacation

**Comment by josenikhid97** [comment] 2022-10-11 06:58
How can I send u the tree file because it seems the file is large anyways
of sending it to you is possible ?
Let me know how can I send it to you

**Comment by computations** [comment] 2022-10-11 08:32
I'm not sure how large it is, but compressing the file (with zip or 7zip) should reduce the size of the file quite a bit. From there, maybe it is possible to upload it to google drive and send me a link?

**Comment by computations** [comment] 2023-03-15 07:50
This ticket is several months old with no reply, I am closing the issue

**Closed as completed by computations** 2023-03-15 07:50 UTC
